{{- if .Values.llamastack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-inference-model-secret
  namespace: {{ include "competitor-analysis.namespace" . }}
  labels:
    {{- include "competitor-analysis.llamastack.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  INFERENCE_MODEL: {{ .Values.llamastack.vllm.inferenceModel | quote }}
  VLLM_URL: {{ .Values.llamastack.vllm.url | quote }}
  VLLM_TLS_VERIFY: {{ .Values.llamastack.vllm.tlsVerify | quote }}
  VLLM_API_TOKEN: {{ .Values.llamastack.vllm.apiToken | quote }}
{{- end }}

