apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "competitor-analysis.namespace" . }}
  labels:
    {{- include "competitor-analysis.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

