{{- if .Values.milvus.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: milvus-secret
  namespace: {{ include "competitor-analysis.namespace" . }}
  labels:
    {{- include "competitor-analysis.milvus.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  root-password: {{ .Values.milvus.credentials.rootPassword | quote }}
{{- end }}

