{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: {{ include "competitor-analysis.namespace" . }}
  labels:
    {{- include "competitor-analysis.minio.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.minio.storage.storageClassName }}
  storageClassName: {{ .Values.minio.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.storage.size }}
  volumeMode: Filesystem
{{- end }}

