{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pipeline.secretName }}
  namespace: {{ include "competitor-analysis.namespace" . }}
  labels:
    {{- include "competitor-analysis.minio.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  # Minio credentials
  # Ensure that the user is at least 3 characters long and the password at least 8
  {{ include "competitor-analysis.minio.secretUserKey" . }}: {{ .Values.minio.credentials.rootUser | quote }}
  {{ include "competitor-analysis.minio.secretPasswordKey" . }}: {{ .Values.minio.credentials.rootPassword | quote }}
{{- end }}

