{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "competitor-analysis.minio.serviceName" . }}
  namespace: {{ include "competitor-analysis.namespace" . }}
  labels:
    {{- include "competitor-analysis.minio.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.minio.service.type }}
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.minio.service.apiPort }}
      targetPort: {{ .Values.minio.service.apiPort }}
    - name: ui
      protocol: TCP
      port: {{ .Values.minio.service.consolePort }}
      targetPort: {{ .Values.minio.service.consolePort }}
  selector:
    {{- include "competitor-analysis.minio.selectorLabels" . | nindent 4 }}
{{- end }}

